version: '3.9'

services:
  app:
    build:
      context: .
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    depends_on:
      - db 

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"

  pgadmin:
    # image: dpage/pgadmin4
    image: pgadmin4/pgadmin4
    restart: always
    environment:
      # - PGADMIN_DEFAULT_EMAIL= admin@example.com
      # - PGADMIN_DEFAULT_PASSWORD = admin
      - PGADMIN_DEFAULT_EMAIL: admin@example.com
      - PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
