channels:
- conda-forge
dependencies:
- python=3.11.2
- pip<=25.0
- pip:
  - mlflow==2.20.1
  - cloudpickle==3.1.1
  - numpy==1.26.4
  - psutil==6.1.1
  - scikit-learn==1.4.2
  - scipy==1.11.4
name: mlflow-env
