name: Build, Analyze, Scan

on: 
  push:
    branches:
      - main

jobs:
  build_analyze_scan:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl start docker
          sudo systemctl enable docker
          docker --version  # ✅ Verify Docker installed

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version  # ✅ Verify Docker Compose installed

      - name: Build Docker Image
        run: |
          docker-compose -f docker-compose.yml build
          docker images  # ✅ List images for debugging

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Tag and Push Docker Image
        run: |
          docker tag mlops_app:latest tejas9111/webapp:latest
          docker push tejas9111/webapp:latest
        env:
          DOCKER_CLI_ACI: 1
